package com.mtgo.decklistmanager.util

import com.mtgo.decklistmanager.R
import java.util.Locale

/** Local Scryfall symbol artwork; see docs/MANA_SYMBOLS.md. */
object ManaSymbols {
    private val resources = mapOf(
        "T" to R.drawable.mana_t,
        "Q" to R.drawable.mana_q,
        "E" to R.drawable.mana_e,
        "P" to R.drawable.mana_p,
        "PW" to R.drawable.mana_pw,
        "CHAOS" to R.drawable.mana_chaos,
        "A" to R.drawable.mana_a,
        "TK" to R.drawable.mana_tk,
        "X" to R.drawable.mana_x,
        "Y" to R.drawable.mana_y,
        "Z" to R.drawable.mana_z,
        "0" to R.drawable.mana_0,
        "½" to R.drawable.mana_half,
        "1" to R.drawable.mana_1,
        "2" to R.drawable.mana_2,
        "3" to R.drawable.mana_3,
        "4" to R.drawable.mana_4,
        "5" to R.drawable.mana_5,
        "6" to R.drawable.mana_6,
        "7" to R.drawable.mana_7,
        "8" to R.drawable.mana_8,
        "9" to R.drawable.mana_9,
        "10" to R.drawable.mana_10,
        "11" to R.drawable.mana_11,
        "12" to R.drawable.mana_12,
        "13" to R.drawable.mana_13,
        "14" to R.drawable.mana_14,
        "15" to R.drawable.mana_15,
        "16" to R.drawable.mana_16,
        "17" to R.drawable.mana_17,
        "18" to R.drawable.mana_18,
        "19" to R.drawable.mana_19,
        "20" to R.drawable.mana_20,
        "100" to R.drawable.mana_100,
        "1000000" to R.drawable.mana_1000000,
        "∞" to R.drawable.mana_infinity,
        "W/U" to R.drawable.mana_wu,
        "W/B" to R.drawable.mana_wb,
        "B/R" to R.drawable.mana_br,
        "B/G" to R.drawable.mana_bg,
        "U/B" to R.drawable.mana_ub,
        "U/R" to R.drawable.mana_ur,
        "R/G" to R.drawable.mana_rg,
        "R/W" to R.drawable.mana_rw,
        "G/W" to R.drawable.mana_gw,
        "G/U" to R.drawable.mana_gu,
        "B/G/P" to R.drawable.mana_bgp,
        "B/R/P" to R.drawable.mana_brp,
        "G/U/P" to R.drawable.mana_gup,
        "G/W/P" to R.drawable.mana_gwp,
        "R/G/P" to R.drawable.mana_rgp,
        "R/W/P" to R.drawable.mana_rwp,
        "U/B/P" to R.drawable.mana_ubp,
        "U/R/P" to R.drawable.mana_urp,
        "W/B/P" to R.drawable.mana_wbp,
        "W/U/P" to R.drawable.mana_wup,
        "C/W" to R.drawable.mana_cw,
        "C/U" to R.drawable.mana_cu,
        "C/B" to R.drawable.mana_cb,
        "C/R" to R.drawable.mana_cr,
        "C/G" to R.drawable.mana_cg,
        "2/W" to R.drawable.mana_2w,
        "2/U" to R.drawable.mana_2u,
        "2/B" to R.drawable.mana_2b,
        "2/R" to R.drawable.mana_2r,
        "2/G" to R.drawable.mana_2g,
        "H" to R.drawable.mana_h,
        "W/P" to R.drawable.mana_wp,
        "U/P" to R.drawable.mana_up,
        "B/P" to R.drawable.mana_bp,
        "R/P" to R.drawable.mana_rp,
        "G/P" to R.drawable.mana_gp,
        "C/P" to R.drawable.mana_cp,
        "HW" to R.drawable.mana_hw,
        "HR" to R.drawable.mana_hr,
        "W" to R.drawable.mana_w,
        "U" to R.drawable.mana_u,
        "B" to R.drawable.mana_b,
        "R" to R.drawable.mana_r,
        "G" to R.drawable.mana_g,
        "C" to R.drawable.mana_c,
        "S" to R.drawable.mana_s,
        "L" to R.drawable.mana_l,
        "D" to R.drawable.mana_d
    )
    fun resourceFor(symbol: String): Int? {
        val key = symbol.uppercase(Locale.ROOT)
        return resources[key] ?: resources[key.split('/').reversed().joinToString("/")]
    }
}
